### ISSUE TITLE
Security issue in brace-expansion dependency 

### ISSUE THREAD

**Issue by BillHodghead** [mojaloop/dfsp-admin#2]
The cause of this bug is several outdated dependencies. 
See file https://github.com/mojaloop/dfsp-admin/blob/master/security_scan.md for a list of the issues

see also: https://github.com/mojaloop/dfsp-admin/network/dependencies

We found a potential security vulnerability in one of your dependencies.
The brace-expansion dependency defined in package.json has a known moderate severity security vulnerability in version range < 1.1.7 and should be updated.

**Comment by vencislavdimitrov** [comment]
the dependency is updated with the latest commit
